export let Genres: { question: string; id: number; choices: ({ val: string; text: string; key: number } | { val: string; text: string; key: number } | { val: string; text: string; key: number } | { val: string; text: string; key: number })[] };
Genres = {
    question:
        "Select 0 to 3 genres:",
    id: 5,
    choices: [
        {text: "afrobeat", val: "afrobeat", key: 0},
        {text: "alt-rock", val: "alt-rock", key: 1},
        {text: "alternative", val: "alternative", key: 2},
        {text: "blues", val: "blues", key: 3},
        {text: "brazil", val: "brazil", key: 4},
        {text: "british", val: "british", key: 5},
        {text: "chill", val: "chill", key: 6},
        {text: "classical", val: "classical", key: 7},
        {text: "club", val: "club", key: 8},
        {text: "country", val: "country", key: 9},
        {text: "dance", val: "dance", key: 10},
        {text: "disco", val: "disco", key: 11},
        {text: "dubstep", val: "dubstep", key: 12},
        {text: "edm", val: "edm", key: 13},
        {text: "emo", val: "emo", key: 14},
        {text: "folk", val: "folk", key: 15},
        {text: "french", val: "french", key: 16},
        {text: "funk", val: "funk", key: 17},
        {text: "garage", val: "garage", key: 18},
        {text: "german", val: "german", key: 19},
        {text: "grunge", val: "grunge", key: 20},
        {text: "hardcore", val: "hardcore", key: 21},
        {text: "hip-hop", val: "hip-hop", key: 22},
        {text: "indian", val: "indian", key: 23},
        {text: "indie", val: "indie", key: 24},
        {text: "indie-pop", val: "indie-pop", key: 25},
        {text: "industrial", val: "industrial", key: 26},
        {text: "j-pop", val: "j-pop", key: 27},
        {text: "jazz", val: "jazz", key: 28},
        {text: "k-pop", val: "k-pop", key: 29},
        {text: "latino", val: "latino", key: 30},
        {text: "malay", val: "malay", key: 31 },
        {text: "mandopop", val: "mandopop", key: 32},
        {text: "metal", val: "metal", key: 33},
        {text: "new-age", val: "new-age", key: 34},
        {text: "new-release", val: "new-release", key: 35},
        {text: "opera", val: "opera", key: 36},
        {text: "party", val: "party",key: 37},
        {text: "philippines-opm", val: "philippines-opm", key: 38},
        {text: "pop", val: "pop", key: 39},
        {text: "punk", val: "punk", key: 40},
        {text: "punk-rock", val: "punk-rock", key: 41},
        {text: "r-n-b", val: "r-n-b", key: 42},
        {text: "rainy-day", val: "rainy-day", key: 43},
        {text: "reggae", val: "reggae", key: 44},
        {text: "rock", val: "rock", key: 45},
        {text: "sad", val: "sad", key: 46},
        {text: "samba", val: "samba", key: 47},
        {text: "sertanejo", val: "sertanejo", key: 48},
        {text: "sleep", val: "sleep", key: 49},
        {text: "soul", val: "soul", key: 50},
        {text: "spanish", val: "spanish", key: 51},
        {text: "synth-pop", val: "synth-pop", key: 52},
        {text: "techno", val: "techno", key: 53},
        {text: "work-out", val: "work-out", key: 54},
        {text: "world-music", val: "world-music", key: 55},
    ]
};
